/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as EditorRouteImport } from './routes/editor';
import { Route as ContractsRouteImport } from './routes/contracts';
import { Route as IndexRouteImport } from './routes/index';
import { Route as EditorIndexRouteImport } from './routes/editor.index';
import { Route as ContractsIndexRouteImport } from './routes/contracts.index';
import { Route as EditorNewRouteImport } from './routes/editor.new';
import { Route as EditorProjectIdRouteImport } from './routes/editor.$projectId';
import { Route as ContractsAddressRouteImport } from './routes/contracts.$address';

const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any);
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorRoute,
} as any);
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContractsRoute,
} as any);
const EditorNewRoute = EditorNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EditorRoute,
} as any);
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => EditorRoute,
} as any);
const ContractsAddressRoute = ContractsAddressRouteImport.update({
  id: '/$address',
  path: '/$address',
  getParentRoute: () => ContractsRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/contracts': typeof ContractsRouteWithChildren;
  '/editor': typeof EditorRouteWithChildren;
  '/contracts/$address': typeof ContractsAddressRoute;
  '/editor/$projectId': typeof EditorProjectIdRoute;
  '/editor/new': typeof EditorNewRoute;
  '/contracts/': typeof ContractsIndexRoute;
  '/editor/': typeof EditorIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/contracts/$address': typeof ContractsAddressRoute;
  '/editor/$projectId': typeof EditorProjectIdRoute;
  '/editor/new': typeof EditorNewRoute;
  '/contracts': typeof ContractsIndexRoute;
  '/editor': typeof EditorIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/contracts': typeof ContractsRouteWithChildren;
  '/editor': typeof EditorRouteWithChildren;
  '/contracts/$address': typeof ContractsAddressRoute;
  '/editor/$projectId': typeof EditorProjectIdRoute;
  '/editor/new': typeof EditorNewRoute;
  '/contracts/': typeof ContractsIndexRoute;
  '/editor/': typeof EditorIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/contracts'
    | '/editor'
    | '/contracts/$address'
    | '/editor/$projectId'
    | '/editor/new'
    | '/contracts/'
    | '/editor/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/contracts/$address' | '/editor/$projectId' | '/editor/new' | '/contracts' | '/editor';
  id:
    | '__root__'
    | '/'
    | '/contracts'
    | '/editor'
    | '/contracts/$address'
    | '/editor/$projectId'
    | '/editor/new'
    | '/contracts/'
    | '/editor/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ContractsRoute: typeof ContractsRouteWithChildren;
  EditorRoute: typeof EditorRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor': {
      id: '/editor';
      path: '/editor';
      fullPath: '/editor';
      preLoaderRoute: typeof EditorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/contracts': {
      id: '/contracts';
      path: '/contracts';
      fullPath: '/contracts';
      preLoaderRoute: typeof ContractsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/editor/': {
      id: '/editor/';
      path: '/';
      fullPath: '/editor/';
      preLoaderRoute: typeof EditorIndexRouteImport;
      parentRoute: typeof EditorRoute;
    };
    '/contracts/': {
      id: '/contracts/';
      path: '/';
      fullPath: '/contracts/';
      preLoaderRoute: typeof ContractsIndexRouteImport;
      parentRoute: typeof ContractsRoute;
    };
    '/editor/new': {
      id: '/editor/new';
      path: '/new';
      fullPath: '/editor/new';
      preLoaderRoute: typeof EditorNewRouteImport;
      parentRoute: typeof EditorRoute;
    };
    '/editor/$projectId': {
      id: '/editor/$projectId';
      path: '/$projectId';
      fullPath: '/editor/$projectId';
      preLoaderRoute: typeof EditorProjectIdRouteImport;
      parentRoute: typeof EditorRoute;
    };
    '/contracts/$address': {
      id: '/contracts/$address';
      path: '/$address';
      fullPath: '/contracts/$address';
      preLoaderRoute: typeof ContractsAddressRouteImport;
      parentRoute: typeof ContractsRoute;
    };
  }
}

interface ContractsRouteChildren {
  ContractsAddressRoute: typeof ContractsAddressRoute;
  ContractsIndexRoute: typeof ContractsIndexRoute;
}

const ContractsRouteChildren: ContractsRouteChildren = {
  ContractsAddressRoute: ContractsAddressRoute,
  ContractsIndexRoute: ContractsIndexRoute,
};

const ContractsRouteWithChildren = ContractsRoute._addFileChildren(ContractsRouteChildren);

interface EditorRouteChildren {
  EditorProjectIdRoute: typeof EditorProjectIdRoute;
  EditorNewRoute: typeof EditorNewRoute;
  EditorIndexRoute: typeof EditorIndexRoute;
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorProjectIdRoute: EditorProjectIdRoute,
  EditorNewRoute: EditorNewRoute,
  EditorIndexRoute: EditorIndexRoute,
};

const EditorRouteWithChildren = EditorRoute._addFileChildren(EditorRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractsRoute: ContractsRouteWithChildren,
  EditorRoute: EditorRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
