/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignRouteImport } from './routes/sign'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTokenApprovalsRouteImport } from './routes/portal/token-approvals'
import { Route as PortalTip403FactoryRouteImport } from './routes/portal/tip403-factory'
import { Route as PortalTip20StudioRouteImport } from './routes/portal/tip20-studio'
import { Route as PortalSettingsRouteImport } from './routes/portal/settings'
import { Route as PortalSendRouteImport } from './routes/portal/send'
import { Route as PortalScheduledPaymentsRouteImport } from './routes/portal/scheduled-payments'
import { Route as PortalRewardsRouteImport } from './routes/portal/rewards'
import { Route as PortalRecurringPaymentsRouteImport } from './routes/portal/recurring-payments'
import { Route as PortalReceiveRouteImport } from './routes/portal/receive'
import { Route as PortalFeeAmmSwapRouteImport } from './routes/portal/fee-amm-swap'
import { Route as PortalFeeAmmLiquidityRouteImport } from './routes/portal/fee-amm-liquidity'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as PortalContactsRouteImport } from './routes/portal/contacts'
import { Route as PortalConnectedAppsRouteImport } from './routes/portal/connected-apps'
import { Route as PortalBatchPaymentsRouteImport } from './routes/portal/batch-payments'
import { Route as PortalAccessKeysRouteImport } from './routes/portal/access-keys'
import { Route as PortalTip403FactoryIndexRouteImport } from './routes/portal/tip403-factory.index'
import { Route as PortalTip20StudioIndexRouteImport } from './routes/portal/tip20-studio.index'
import { Route as PortalTip403FactoryPolicyIdRouteImport } from './routes/portal/tip403-factory.$policyId'
import { Route as PortalTip20StudioAddressRouteImport } from './routes/portal/tip20-studio.$address'
import { Route as PortalSettingsFeeTokenRouteImport } from './routes/portal/settings.fee-token'
import { Route as PortalSettingsCustomTokensRouteImport } from './routes/portal/settings.custom-tokens'
import { Route as PortalTip403FactoryPolicyIdOverviewRouteImport } from './routes/portal/tip403-factory.$policyId.overview'
import { Route as PortalTip20StudioAddressRewardsRouteImport } from './routes/portal/tip20-studio.$address.rewards'
import { Route as PortalTip20StudioAddressOverviewRouteImport } from './routes/portal/tip20-studio.$address.overview'

const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenApprovalsRoute = PortalTokenApprovalsRouteImport.update({
  id: '/token-approvals',
  path: '/token-approvals',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTip403FactoryRoute = PortalTip403FactoryRouteImport.update({
  id: '/tip403-factory',
  path: '/tip403-factory',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTip20StudioRoute = PortalTip20StudioRouteImport.update({
  id: '/tip20-studio',
  path: '/tip20-studio',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSendRoute = PortalSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => PortalRoute,
} as any)
const PortalScheduledPaymentsRoute = PortalScheduledPaymentsRouteImport.update({
  id: '/scheduled-payments',
  path: '/scheduled-payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRewardsRoute = PortalRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRecurringPaymentsRoute = PortalRecurringPaymentsRouteImport.update({
  id: '/recurring-payments',
  path: '/recurring-payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReceiveRoute = PortalReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFeeAmmSwapRoute = PortalFeeAmmSwapRouteImport.update({
  id: '/fee-amm-swap',
  path: '/fee-amm-swap',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFeeAmmLiquidityRoute = PortalFeeAmmLiquidityRouteImport.update({
  id: '/fee-amm-liquidity',
  path: '/fee-amm-liquidity',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContactsRoute = PortalContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalConnectedAppsRoute = PortalConnectedAppsRouteImport.update({
  id: '/connected-apps',
  path: '/connected-apps',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBatchPaymentsRoute = PortalBatchPaymentsRouteImport.update({
  id: '/batch-payments',
  path: '/batch-payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccessKeysRoute = PortalAccessKeysRouteImport.update({
  id: '/access-keys',
  path: '/access-keys',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTip403FactoryIndexRoute =
  PortalTip403FactoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PortalTip403FactoryRoute,
  } as any)
const PortalTip20StudioIndexRoute = PortalTip20StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalTip20StudioRoute,
} as any)
const PortalTip403FactoryPolicyIdRoute =
  PortalTip403FactoryPolicyIdRouteImport.update({
    id: '/$policyId',
    path: '/$policyId',
    getParentRoute: () => PortalTip403FactoryRoute,
  } as any)
const PortalTip20StudioAddressRoute =
  PortalTip20StudioAddressRouteImport.update({
    id: '/$address',
    path: '/$address',
    getParentRoute: () => PortalTip20StudioRoute,
  } as any)
const PortalSettingsFeeTokenRoute = PortalSettingsFeeTokenRouteImport.update({
  id: '/fee-token',
  path: '/fee-token',
  getParentRoute: () => PortalSettingsRoute,
} as any)
const PortalSettingsCustomTokensRoute =
  PortalSettingsCustomTokensRouteImport.update({
    id: '/custom-tokens',
    path: '/custom-tokens',
    getParentRoute: () => PortalSettingsRoute,
  } as any)
const PortalTip403FactoryPolicyIdOverviewRoute =
  PortalTip403FactoryPolicyIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => PortalTip403FactoryPolicyIdRoute,
  } as any)
const PortalTip20StudioAddressRewardsRoute =
  PortalTip20StudioAddressRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => PortalTip20StudioAddressRoute,
  } as any)
const PortalTip20StudioAddressOverviewRoute =
  PortalTip20StudioAddressOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => PortalTip20StudioAddressRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/embed': typeof EmbedRoute
  '/portal': typeof PortalRouteWithChildren
  '/sign': typeof SignRoute
  '/portal/access-keys': typeof PortalAccessKeysRoute
  '/portal/batch-payments': typeof PortalBatchPaymentsRoute
  '/portal/connected-apps': typeof PortalConnectedAppsRoute
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/fee-amm-liquidity': typeof PortalFeeAmmLiquidityRoute
  '/portal/fee-amm-swap': typeof PortalFeeAmmSwapRoute
  '/portal/receive': typeof PortalReceiveRoute
  '/portal/recurring-payments': typeof PortalRecurringPaymentsRoute
  '/portal/rewards': typeof PortalRewardsRoute
  '/portal/scheduled-payments': typeof PortalScheduledPaymentsRoute
  '/portal/send': typeof PortalSendRoute
  '/portal/settings': typeof PortalSettingsRouteWithChildren
  '/portal/tip20-studio': typeof PortalTip20StudioRouteWithChildren
  '/portal/tip403-factory': typeof PortalTip403FactoryRouteWithChildren
  '/portal/token-approvals': typeof PortalTokenApprovalsRoute
  '/portal/settings/custom-tokens': typeof PortalSettingsCustomTokensRoute
  '/portal/settings/fee-token': typeof PortalSettingsFeeTokenRoute
  '/portal/tip20-studio/$address': typeof PortalTip20StudioAddressRouteWithChildren
  '/portal/tip403-factory/$policyId': typeof PortalTip403FactoryPolicyIdRouteWithChildren
  '/portal/tip20-studio/': typeof PortalTip20StudioIndexRoute
  '/portal/tip403-factory/': typeof PortalTip403FactoryIndexRoute
  '/portal/tip20-studio/$address/overview': typeof PortalTip20StudioAddressOverviewRoute
  '/portal/tip20-studio/$address/rewards': typeof PortalTip20StudioAddressRewardsRoute
  '/portal/tip403-factory/$policyId/overview': typeof PortalTip403FactoryPolicyIdOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/embed': typeof EmbedRoute
  '/portal': typeof PortalRouteWithChildren
  '/sign': typeof SignRoute
  '/portal/access-keys': typeof PortalAccessKeysRoute
  '/portal/batch-payments': typeof PortalBatchPaymentsRoute
  '/portal/connected-apps': typeof PortalConnectedAppsRoute
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/fee-amm-liquidity': typeof PortalFeeAmmLiquidityRoute
  '/portal/fee-amm-swap': typeof PortalFeeAmmSwapRoute
  '/portal/receive': typeof PortalReceiveRoute
  '/portal/recurring-payments': typeof PortalRecurringPaymentsRoute
  '/portal/rewards': typeof PortalRewardsRoute
  '/portal/scheduled-payments': typeof PortalScheduledPaymentsRoute
  '/portal/send': typeof PortalSendRoute
  '/portal/settings': typeof PortalSettingsRouteWithChildren
  '/portal/token-approvals': typeof PortalTokenApprovalsRoute
  '/portal/settings/custom-tokens': typeof PortalSettingsCustomTokensRoute
  '/portal/settings/fee-token': typeof PortalSettingsFeeTokenRoute
  '/portal/tip20-studio/$address': typeof PortalTip20StudioAddressRouteWithChildren
  '/portal/tip403-factory/$policyId': typeof PortalTip403FactoryPolicyIdRouteWithChildren
  '/portal/tip20-studio': typeof PortalTip20StudioIndexRoute
  '/portal/tip403-factory': typeof PortalTip403FactoryIndexRoute
  '/portal/tip20-studio/$address/overview': typeof PortalTip20StudioAddressOverviewRoute
  '/portal/tip20-studio/$address/rewards': typeof PortalTip20StudioAddressRewardsRoute
  '/portal/tip403-factory/$policyId/overview': typeof PortalTip403FactoryPolicyIdOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/embed': typeof EmbedRoute
  '/portal': typeof PortalRouteWithChildren
  '/sign': typeof SignRoute
  '/portal/access-keys': typeof PortalAccessKeysRoute
  '/portal/batch-payments': typeof PortalBatchPaymentsRoute
  '/portal/connected-apps': typeof PortalConnectedAppsRoute
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/fee-amm-liquidity': typeof PortalFeeAmmLiquidityRoute
  '/portal/fee-amm-swap': typeof PortalFeeAmmSwapRoute
  '/portal/receive': typeof PortalReceiveRoute
  '/portal/recurring-payments': typeof PortalRecurringPaymentsRoute
  '/portal/rewards': typeof PortalRewardsRoute
  '/portal/scheduled-payments': typeof PortalScheduledPaymentsRoute
  '/portal/send': typeof PortalSendRoute
  '/portal/settings': typeof PortalSettingsRouteWithChildren
  '/portal/tip20-studio': typeof PortalTip20StudioRouteWithChildren
  '/portal/tip403-factory': typeof PortalTip403FactoryRouteWithChildren
  '/portal/token-approvals': typeof PortalTokenApprovalsRoute
  '/portal/settings/custom-tokens': typeof PortalSettingsCustomTokensRoute
  '/portal/settings/fee-token': typeof PortalSettingsFeeTokenRoute
  '/portal/tip20-studio/$address': typeof PortalTip20StudioAddressRouteWithChildren
  '/portal/tip403-factory/$policyId': typeof PortalTip403FactoryPolicyIdRouteWithChildren
  '/portal/tip20-studio/': typeof PortalTip20StudioIndexRoute
  '/portal/tip403-factory/': typeof PortalTip403FactoryIndexRoute
  '/portal/tip20-studio/$address/overview': typeof PortalTip20StudioAddressOverviewRoute
  '/portal/tip20-studio/$address/rewards': typeof PortalTip20StudioAddressRewardsRoute
  '/portal/tip403-factory/$policyId/overview': typeof PortalTip403FactoryPolicyIdOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/embed'
    | '/portal'
    | '/sign'
    | '/portal/access-keys'
    | '/portal/batch-payments'
    | '/portal/connected-apps'
    | '/portal/contacts'
    | '/portal/dashboard'
    | '/portal/fee-amm-liquidity'
    | '/portal/fee-amm-swap'
    | '/portal/receive'
    | '/portal/recurring-payments'
    | '/portal/rewards'
    | '/portal/scheduled-payments'
    | '/portal/send'
    | '/portal/settings'
    | '/portal/tip20-studio'
    | '/portal/tip403-factory'
    | '/portal/token-approvals'
    | '/portal/settings/custom-tokens'
    | '/portal/settings/fee-token'
    | '/portal/tip20-studio/$address'
    | '/portal/tip403-factory/$policyId'
    | '/portal/tip20-studio/'
    | '/portal/tip403-factory/'
    | '/portal/tip20-studio/$address/overview'
    | '/portal/tip20-studio/$address/rewards'
    | '/portal/tip403-factory/$policyId/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/embed'
    | '/portal'
    | '/sign'
    | '/portal/access-keys'
    | '/portal/batch-payments'
    | '/portal/connected-apps'
    | '/portal/contacts'
    | '/portal/dashboard'
    | '/portal/fee-amm-liquidity'
    | '/portal/fee-amm-swap'
    | '/portal/receive'
    | '/portal/recurring-payments'
    | '/portal/rewards'
    | '/portal/scheduled-payments'
    | '/portal/send'
    | '/portal/settings'
    | '/portal/token-approvals'
    | '/portal/settings/custom-tokens'
    | '/portal/settings/fee-token'
    | '/portal/tip20-studio/$address'
    | '/portal/tip403-factory/$policyId'
    | '/portal/tip20-studio'
    | '/portal/tip403-factory'
    | '/portal/tip20-studio/$address/overview'
    | '/portal/tip20-studio/$address/rewards'
    | '/portal/tip403-factory/$policyId/overview'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/embed'
    | '/portal'
    | '/sign'
    | '/portal/access-keys'
    | '/portal/batch-payments'
    | '/portal/connected-apps'
    | '/portal/contacts'
    | '/portal/dashboard'
    | '/portal/fee-amm-liquidity'
    | '/portal/fee-amm-swap'
    | '/portal/receive'
    | '/portal/recurring-payments'
    | '/portal/rewards'
    | '/portal/scheduled-payments'
    | '/portal/send'
    | '/portal/settings'
    | '/portal/tip20-studio'
    | '/portal/tip403-factory'
    | '/portal/token-approvals'
    | '/portal/settings/custom-tokens'
    | '/portal/settings/fee-token'
    | '/portal/tip20-studio/$address'
    | '/portal/tip403-factory/$policyId'
    | '/portal/tip20-studio/'
    | '/portal/tip403-factory/'
    | '/portal/tip20-studio/$address/overview'
    | '/portal/tip20-studio/$address/rewards'
    | '/portal/tip403-factory/$policyId/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  EmbedRoute: typeof EmbedRoute
  PortalRoute: typeof PortalRouteWithChildren
  SignRoute: typeof SignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/token-approvals': {
      id: '/portal/token-approvals'
      path: '/token-approvals'
      fullPath: '/portal/token-approvals'
      preLoaderRoute: typeof PortalTokenApprovalsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tip403-factory': {
      id: '/portal/tip403-factory'
      path: '/tip403-factory'
      fullPath: '/portal/tip403-factory'
      preLoaderRoute: typeof PortalTip403FactoryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tip20-studio': {
      id: '/portal/tip20-studio'
      path: '/tip20-studio'
      fullPath: '/portal/tip20-studio'
      preLoaderRoute: typeof PortalTip20StudioRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/send': {
      id: '/portal/send'
      path: '/send'
      fullPath: '/portal/send'
      preLoaderRoute: typeof PortalSendRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/scheduled-payments': {
      id: '/portal/scheduled-payments'
      path: '/scheduled-payments'
      fullPath: '/portal/scheduled-payments'
      preLoaderRoute: typeof PortalScheduledPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/rewards': {
      id: '/portal/rewards'
      path: '/rewards'
      fullPath: '/portal/rewards'
      preLoaderRoute: typeof PortalRewardsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/recurring-payments': {
      id: '/portal/recurring-payments'
      path: '/recurring-payments'
      fullPath: '/portal/recurring-payments'
      preLoaderRoute: typeof PortalRecurringPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/receive': {
      id: '/portal/receive'
      path: '/receive'
      fullPath: '/portal/receive'
      preLoaderRoute: typeof PortalReceiveRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/fee-amm-swap': {
      id: '/portal/fee-amm-swap'
      path: '/fee-amm-swap'
      fullPath: '/portal/fee-amm-swap'
      preLoaderRoute: typeof PortalFeeAmmSwapRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/fee-amm-liquidity': {
      id: '/portal/fee-amm-liquidity'
      path: '/fee-amm-liquidity'
      fullPath: '/portal/fee-amm-liquidity'
      preLoaderRoute: typeof PortalFeeAmmLiquidityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contacts': {
      id: '/portal/contacts'
      path: '/contacts'
      fullPath: '/portal/contacts'
      preLoaderRoute: typeof PortalContactsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/connected-apps': {
      id: '/portal/connected-apps'
      path: '/connected-apps'
      fullPath: '/portal/connected-apps'
      preLoaderRoute: typeof PortalConnectedAppsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/batch-payments': {
      id: '/portal/batch-payments'
      path: '/batch-payments'
      fullPath: '/portal/batch-payments'
      preLoaderRoute: typeof PortalBatchPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/access-keys': {
      id: '/portal/access-keys'
      path: '/access-keys'
      fullPath: '/portal/access-keys'
      preLoaderRoute: typeof PortalAccessKeysRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tip403-factory/': {
      id: '/portal/tip403-factory/'
      path: '/'
      fullPath: '/portal/tip403-factory/'
      preLoaderRoute: typeof PortalTip403FactoryIndexRouteImport
      parentRoute: typeof PortalTip403FactoryRoute
    }
    '/portal/tip20-studio/': {
      id: '/portal/tip20-studio/'
      path: '/'
      fullPath: '/portal/tip20-studio/'
      preLoaderRoute: typeof PortalTip20StudioIndexRouteImport
      parentRoute: typeof PortalTip20StudioRoute
    }
    '/portal/tip403-factory/$policyId': {
      id: '/portal/tip403-factory/$policyId'
      path: '/$policyId'
      fullPath: '/portal/tip403-factory/$policyId'
      preLoaderRoute: typeof PortalTip403FactoryPolicyIdRouteImport
      parentRoute: typeof PortalTip403FactoryRoute
    }
    '/portal/tip20-studio/$address': {
      id: '/portal/tip20-studio/$address'
      path: '/$address'
      fullPath: '/portal/tip20-studio/$address'
      preLoaderRoute: typeof PortalTip20StudioAddressRouteImport
      parentRoute: typeof PortalTip20StudioRoute
    }
    '/portal/settings/fee-token': {
      id: '/portal/settings/fee-token'
      path: '/fee-token'
      fullPath: '/portal/settings/fee-token'
      preLoaderRoute: typeof PortalSettingsFeeTokenRouteImport
      parentRoute: typeof PortalSettingsRoute
    }
    '/portal/settings/custom-tokens': {
      id: '/portal/settings/custom-tokens'
      path: '/custom-tokens'
      fullPath: '/portal/settings/custom-tokens'
      preLoaderRoute: typeof PortalSettingsCustomTokensRouteImport
      parentRoute: typeof PortalSettingsRoute
    }
    '/portal/tip403-factory/$policyId/overview': {
      id: '/portal/tip403-factory/$policyId/overview'
      path: '/overview'
      fullPath: '/portal/tip403-factory/$policyId/overview'
      preLoaderRoute: typeof PortalTip403FactoryPolicyIdOverviewRouteImport
      parentRoute: typeof PortalTip403FactoryPolicyIdRoute
    }
    '/portal/tip20-studio/$address/rewards': {
      id: '/portal/tip20-studio/$address/rewards'
      path: '/rewards'
      fullPath: '/portal/tip20-studio/$address/rewards'
      preLoaderRoute: typeof PortalTip20StudioAddressRewardsRouteImport
      parentRoute: typeof PortalTip20StudioAddressRoute
    }
    '/portal/tip20-studio/$address/overview': {
      id: '/portal/tip20-studio/$address/overview'
      path: '/overview'
      fullPath: '/portal/tip20-studio/$address/overview'
      preLoaderRoute: typeof PortalTip20StudioAddressOverviewRouteImport
      parentRoute: typeof PortalTip20StudioAddressRoute
    }
  }
}

interface PortalSettingsRouteChildren {
  PortalSettingsCustomTokensRoute: typeof PortalSettingsCustomTokensRoute
  PortalSettingsFeeTokenRoute: typeof PortalSettingsFeeTokenRoute
}

const PortalSettingsRouteChildren: PortalSettingsRouteChildren = {
  PortalSettingsCustomTokensRoute: PortalSettingsCustomTokensRoute,
  PortalSettingsFeeTokenRoute: PortalSettingsFeeTokenRoute,
}

const PortalSettingsRouteWithChildren = PortalSettingsRoute._addFileChildren(
  PortalSettingsRouteChildren,
)

interface PortalTip20StudioAddressRouteChildren {
  PortalTip20StudioAddressOverviewRoute: typeof PortalTip20StudioAddressOverviewRoute
  PortalTip20StudioAddressRewardsRoute: typeof PortalTip20StudioAddressRewardsRoute
}

const PortalTip20StudioAddressRouteChildren: PortalTip20StudioAddressRouteChildren =
  {
    PortalTip20StudioAddressOverviewRoute:
      PortalTip20StudioAddressOverviewRoute,
    PortalTip20StudioAddressRewardsRoute: PortalTip20StudioAddressRewardsRoute,
  }

const PortalTip20StudioAddressRouteWithChildren =
  PortalTip20StudioAddressRoute._addFileChildren(
    PortalTip20StudioAddressRouteChildren,
  )

interface PortalTip20StudioRouteChildren {
  PortalTip20StudioAddressRoute: typeof PortalTip20StudioAddressRouteWithChildren
  PortalTip20StudioIndexRoute: typeof PortalTip20StudioIndexRoute
}

const PortalTip20StudioRouteChildren: PortalTip20StudioRouteChildren = {
  PortalTip20StudioAddressRoute: PortalTip20StudioAddressRouteWithChildren,
  PortalTip20StudioIndexRoute: PortalTip20StudioIndexRoute,
}

const PortalTip20StudioRouteWithChildren =
  PortalTip20StudioRoute._addFileChildren(PortalTip20StudioRouteChildren)

interface PortalTip403FactoryPolicyIdRouteChildren {
  PortalTip403FactoryPolicyIdOverviewRoute: typeof PortalTip403FactoryPolicyIdOverviewRoute
}

const PortalTip403FactoryPolicyIdRouteChildren: PortalTip403FactoryPolicyIdRouteChildren =
  {
    PortalTip403FactoryPolicyIdOverviewRoute:
      PortalTip403FactoryPolicyIdOverviewRoute,
  }

const PortalTip403FactoryPolicyIdRouteWithChildren =
  PortalTip403FactoryPolicyIdRoute._addFileChildren(
    PortalTip403FactoryPolicyIdRouteChildren,
  )

interface PortalTip403FactoryRouteChildren {
  PortalTip403FactoryPolicyIdRoute: typeof PortalTip403FactoryPolicyIdRouteWithChildren
  PortalTip403FactoryIndexRoute: typeof PortalTip403FactoryIndexRoute
}

const PortalTip403FactoryRouteChildren: PortalTip403FactoryRouteChildren = {
  PortalTip403FactoryPolicyIdRoute:
    PortalTip403FactoryPolicyIdRouteWithChildren,
  PortalTip403FactoryIndexRoute: PortalTip403FactoryIndexRoute,
}

const PortalTip403FactoryRouteWithChildren =
  PortalTip403FactoryRoute._addFileChildren(PortalTip403FactoryRouteChildren)

interface PortalRouteChildren {
  PortalAccessKeysRoute: typeof PortalAccessKeysRoute
  PortalBatchPaymentsRoute: typeof PortalBatchPaymentsRoute
  PortalConnectedAppsRoute: typeof PortalConnectedAppsRoute
  PortalContactsRoute: typeof PortalContactsRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalFeeAmmLiquidityRoute: typeof PortalFeeAmmLiquidityRoute
  PortalFeeAmmSwapRoute: typeof PortalFeeAmmSwapRoute
  PortalReceiveRoute: typeof PortalReceiveRoute
  PortalRecurringPaymentsRoute: typeof PortalRecurringPaymentsRoute
  PortalRewardsRoute: typeof PortalRewardsRoute
  PortalScheduledPaymentsRoute: typeof PortalScheduledPaymentsRoute
  PortalSendRoute: typeof PortalSendRoute
  PortalSettingsRoute: typeof PortalSettingsRouteWithChildren
  PortalTip20StudioRoute: typeof PortalTip20StudioRouteWithChildren
  PortalTip403FactoryRoute: typeof PortalTip403FactoryRouteWithChildren
  PortalTokenApprovalsRoute: typeof PortalTokenApprovalsRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccessKeysRoute: PortalAccessKeysRoute,
  PortalBatchPaymentsRoute: PortalBatchPaymentsRoute,
  PortalConnectedAppsRoute: PortalConnectedAppsRoute,
  PortalContactsRoute: PortalContactsRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalFeeAmmLiquidityRoute: PortalFeeAmmLiquidityRoute,
  PortalFeeAmmSwapRoute: PortalFeeAmmSwapRoute,
  PortalReceiveRoute: PortalReceiveRoute,
  PortalRecurringPaymentsRoute: PortalRecurringPaymentsRoute,
  PortalRewardsRoute: PortalRewardsRoute,
  PortalScheduledPaymentsRoute: PortalScheduledPaymentsRoute,
  PortalSendRoute: PortalSendRoute,
  PortalSettingsRoute: PortalSettingsRouteWithChildren,
  PortalTip20StudioRoute: PortalTip20StudioRouteWithChildren,
  PortalTip403FactoryRoute: PortalTip403FactoryRouteWithChildren,
  PortalTokenApprovalsRoute: PortalTokenApprovalsRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  EmbedRoute: EmbedRoute,
  PortalRoute: PortalRouteWithChildren,
  SignRoute: SignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
