name = "tempo-playground"
compatibility_date = "2025-06-01"

pages_build_output_dir = "./dist"

# Serve as SPA
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
