/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTip403FactoryRouteImport } from './routes/portal/tip403-factory'
import { Route as PortalTip20StudioRouteImport } from './routes/portal/tip20-studio'
import { Route as PortalSwapRouteImport } from './routes/portal/swap'
import { Route as PortalSendRouteImport } from './routes/portal/send'
import { Route as PortalScheduledRouteImport } from './routes/portal/scheduled'
import { Route as PortalReceiveRouteImport } from './routes/portal/receive'
import { Route as PortalLiquidityRouteImport } from './routes/portal/liquidity'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as PortalContactsRouteImport } from './routes/portal/contacts'
import { Route as PortalAccessKeysRouteImport } from './routes/portal/access-keys'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTip403FactoryRoute = PortalTip403FactoryRouteImport.update({
  id: '/tip403-factory',
  path: '/tip403-factory',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTip20StudioRoute = PortalTip20StudioRouteImport.update({
  id: '/tip20-studio',
  path: '/tip20-studio',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSwapRoute = PortalSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSendRoute = PortalSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => PortalRoute,
} as any)
const PortalScheduledRoute = PortalScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReceiveRoute = PortalReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLiquidityRoute = PortalLiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContactsRoute = PortalContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccessKeysRoute = PortalAccessKeysRouteImport.update({
  id: '/access-keys',
  path: '/access-keys',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/access-keys': typeof PortalAccessKeysRoute
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/liquidity': typeof PortalLiquidityRoute
  '/portal/receive': typeof PortalReceiveRoute
  '/portal/scheduled': typeof PortalScheduledRoute
  '/portal/send': typeof PortalSendRoute
  '/portal/swap': typeof PortalSwapRoute
  '/portal/tip20-studio': typeof PortalTip20StudioRoute
  '/portal/tip403-factory': typeof PortalTip403FactoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/access-keys': typeof PortalAccessKeysRoute
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/liquidity': typeof PortalLiquidityRoute
  '/portal/receive': typeof PortalReceiveRoute
  '/portal/scheduled': typeof PortalScheduledRoute
  '/portal/send': typeof PortalSendRoute
  '/portal/swap': typeof PortalSwapRoute
  '/portal/tip20-studio': typeof PortalTip20StudioRoute
  '/portal/tip403-factory': typeof PortalTip403FactoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/access-keys': typeof PortalAccessKeysRoute
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/liquidity': typeof PortalLiquidityRoute
  '/portal/receive': typeof PortalReceiveRoute
  '/portal/scheduled': typeof PortalScheduledRoute
  '/portal/send': typeof PortalSendRoute
  '/portal/swap': typeof PortalSwapRoute
  '/portal/tip20-studio': typeof PortalTip20StudioRoute
  '/portal/tip403-factory': typeof PortalTip403FactoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/portal/access-keys'
    | '/portal/contacts'
    | '/portal/dashboard'
    | '/portal/liquidity'
    | '/portal/receive'
    | '/portal/scheduled'
    | '/portal/send'
    | '/portal/swap'
    | '/portal/tip20-studio'
    | '/portal/tip403-factory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/portal/access-keys'
    | '/portal/contacts'
    | '/portal/dashboard'
    | '/portal/liquidity'
    | '/portal/receive'
    | '/portal/scheduled'
    | '/portal/send'
    | '/portal/swap'
    | '/portal/tip20-studio'
    | '/portal/tip403-factory'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/portal/access-keys'
    | '/portal/contacts'
    | '/portal/dashboard'
    | '/portal/liquidity'
    | '/portal/receive'
    | '/portal/scheduled'
    | '/portal/send'
    | '/portal/swap'
    | '/portal/tip20-studio'
    | '/portal/tip403-factory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/tip403-factory': {
      id: '/portal/tip403-factory'
      path: '/tip403-factory'
      fullPath: '/portal/tip403-factory'
      preLoaderRoute: typeof PortalTip403FactoryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tip20-studio': {
      id: '/portal/tip20-studio'
      path: '/tip20-studio'
      fullPath: '/portal/tip20-studio'
      preLoaderRoute: typeof PortalTip20StudioRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/swap': {
      id: '/portal/swap'
      path: '/swap'
      fullPath: '/portal/swap'
      preLoaderRoute: typeof PortalSwapRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/send': {
      id: '/portal/send'
      path: '/send'
      fullPath: '/portal/send'
      preLoaderRoute: typeof PortalSendRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/scheduled': {
      id: '/portal/scheduled'
      path: '/scheduled'
      fullPath: '/portal/scheduled'
      preLoaderRoute: typeof PortalScheduledRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/receive': {
      id: '/portal/receive'
      path: '/receive'
      fullPath: '/portal/receive'
      preLoaderRoute: typeof PortalReceiveRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/liquidity': {
      id: '/portal/liquidity'
      path: '/liquidity'
      fullPath: '/portal/liquidity'
      preLoaderRoute: typeof PortalLiquidityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contacts': {
      id: '/portal/contacts'
      path: '/contacts'
      fullPath: '/portal/contacts'
      preLoaderRoute: typeof PortalContactsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/access-keys': {
      id: '/portal/access-keys'
      path: '/access-keys'
      fullPath: '/portal/access-keys'
      preLoaderRoute: typeof PortalAccessKeysRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAccessKeysRoute: typeof PortalAccessKeysRoute
  PortalContactsRoute: typeof PortalContactsRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLiquidityRoute: typeof PortalLiquidityRoute
  PortalReceiveRoute: typeof PortalReceiveRoute
  PortalScheduledRoute: typeof PortalScheduledRoute
  PortalSendRoute: typeof PortalSendRoute
  PortalSwapRoute: typeof PortalSwapRoute
  PortalTip20StudioRoute: typeof PortalTip20StudioRoute
  PortalTip403FactoryRoute: typeof PortalTip403FactoryRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccessKeysRoute: PortalAccessKeysRoute,
  PortalContactsRoute: PortalContactsRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLiquidityRoute: PortalLiquidityRoute,
  PortalReceiveRoute: PortalReceiveRoute,
  PortalScheduledRoute: PortalScheduledRoute,
  PortalSendRoute: PortalSendRoute,
  PortalSwapRoute: PortalSwapRoute,
  PortalTip20StudioRoute: PortalTip20StudioRoute,
  PortalTip403FactoryRoute: PortalTip403FactoryRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
