/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTip403FactoryRouteImport } from './routes/portal/tip403-factory'
import { Route as PortalTip20StudioRouteImport } from './routes/portal/tip20-studio'
import { Route as PortalSwapRouteImport } from './routes/portal/swap'
import { Route as PortalSendRouteImport } from './routes/portal/send'
import { Route as PortalScheduledRouteImport } from './routes/portal/scheduled'
import { Route as PortalReceiveRouteImport } from './routes/portal/receive'
import { Route as PortalLiquidityRouteImport } from './routes/portal/liquidity'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as PortalContactsRouteImport } from './routes/portal/contacts'
import { Route as PortalTip403FactoryIndexRouteImport } from './routes/portal/tip403-factory.index'
import { Route as PortalTip20StudioIndexRouteImport } from './routes/portal/tip20-studio.index'
import { Route as PortalTip403FactoryPolicyIdRouteImport } from './routes/portal/tip403-factory.$policyId'
import { Route as PortalTip20StudioAddressRouteImport } from './routes/portal/tip20-studio.$address'
import { Route as PortalTip20StudioAddressRewardsRouteImport } from './routes/portal/tip20-studio.$address.rewards'
import { Route as PortalTip20StudioAddressOverviewRouteImport } from './routes/portal/tip20-studio.$address.overview'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTip403FactoryRoute = PortalTip403FactoryRouteImport.update({
  id: '/tip403-factory',
  path: '/tip403-factory',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTip20StudioRoute = PortalTip20StudioRouteImport.update({
  id: '/tip20-studio',
  path: '/tip20-studio',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSwapRoute = PortalSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSendRoute = PortalSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => PortalRoute,
} as any)
const PortalScheduledRoute = PortalScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReceiveRoute = PortalReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLiquidityRoute = PortalLiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContactsRoute = PortalContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTip403FactoryIndexRoute =
  PortalTip403FactoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PortalTip403FactoryRoute,
  } as any)
const PortalTip20StudioIndexRoute = PortalTip20StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalTip20StudioRoute,
} as any)
const PortalTip403FactoryPolicyIdRoute =
  PortalTip403FactoryPolicyIdRouteImport.update({
    id: '/$policyId',
    path: '/$policyId',
    getParentRoute: () => PortalTip403FactoryRoute,
  } as any)
const PortalTip20StudioAddressRoute =
  PortalTip20StudioAddressRouteImport.update({
    id: '/$address',
    path: '/$address',
    getParentRoute: () => PortalTip20StudioRoute,
  } as any)
const PortalTip20StudioAddressRewardsRoute =
  PortalTip20StudioAddressRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => PortalTip20StudioAddressRoute,
  } as any)
const PortalTip20StudioAddressOverviewRoute =
  PortalTip20StudioAddressOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => PortalTip20StudioAddressRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/liquidity': typeof PortalLiquidityRoute
  '/portal/receive': typeof PortalReceiveRoute
  '/portal/scheduled': typeof PortalScheduledRoute
  '/portal/send': typeof PortalSendRoute
  '/portal/swap': typeof PortalSwapRoute
  '/portal/tip20-studio': typeof PortalTip20StudioRouteWithChildren
  '/portal/tip403-factory': typeof PortalTip403FactoryRouteWithChildren
  '/portal/tip20-studio/$address': typeof PortalTip20StudioAddressRouteWithChildren
  '/portal/tip403-factory/$policyId': typeof PortalTip403FactoryPolicyIdRoute
  '/portal/tip20-studio/': typeof PortalTip20StudioIndexRoute
  '/portal/tip403-factory/': typeof PortalTip403FactoryIndexRoute
  '/portal/tip20-studio/$address/overview': typeof PortalTip20StudioAddressOverviewRoute
  '/portal/tip20-studio/$address/rewards': typeof PortalTip20StudioAddressRewardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/liquidity': typeof PortalLiquidityRoute
  '/portal/receive': typeof PortalReceiveRoute
  '/portal/scheduled': typeof PortalScheduledRoute
  '/portal/send': typeof PortalSendRoute
  '/portal/swap': typeof PortalSwapRoute
  '/portal/tip20-studio/$address': typeof PortalTip20StudioAddressRouteWithChildren
  '/portal/tip403-factory/$policyId': typeof PortalTip403FactoryPolicyIdRoute
  '/portal/tip20-studio': typeof PortalTip20StudioIndexRoute
  '/portal/tip403-factory': typeof PortalTip403FactoryIndexRoute
  '/portal/tip20-studio/$address/overview': typeof PortalTip20StudioAddressOverviewRoute
  '/portal/tip20-studio/$address/rewards': typeof PortalTip20StudioAddressRewardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/liquidity': typeof PortalLiquidityRoute
  '/portal/receive': typeof PortalReceiveRoute
  '/portal/scheduled': typeof PortalScheduledRoute
  '/portal/send': typeof PortalSendRoute
  '/portal/swap': typeof PortalSwapRoute
  '/portal/tip20-studio': typeof PortalTip20StudioRouteWithChildren
  '/portal/tip403-factory': typeof PortalTip403FactoryRouteWithChildren
  '/portal/tip20-studio/$address': typeof PortalTip20StudioAddressRouteWithChildren
  '/portal/tip403-factory/$policyId': typeof PortalTip403FactoryPolicyIdRoute
  '/portal/tip20-studio/': typeof PortalTip20StudioIndexRoute
  '/portal/tip403-factory/': typeof PortalTip403FactoryIndexRoute
  '/portal/tip20-studio/$address/overview': typeof PortalTip20StudioAddressOverviewRoute
  '/portal/tip20-studio/$address/rewards': typeof PortalTip20StudioAddressRewardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/portal/contacts'
    | '/portal/dashboard'
    | '/portal/liquidity'
    | '/portal/receive'
    | '/portal/scheduled'
    | '/portal/send'
    | '/portal/swap'
    | '/portal/tip20-studio'
    | '/portal/tip403-factory'
    | '/portal/tip20-studio/$address'
    | '/portal/tip403-factory/$policyId'
    | '/portal/tip20-studio/'
    | '/portal/tip403-factory/'
    | '/portal/tip20-studio/$address/overview'
    | '/portal/tip20-studio/$address/rewards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/portal/contacts'
    | '/portal/dashboard'
    | '/portal/liquidity'
    | '/portal/receive'
    | '/portal/scheduled'
    | '/portal/send'
    | '/portal/swap'
    | '/portal/tip20-studio/$address'
    | '/portal/tip403-factory/$policyId'
    | '/portal/tip20-studio'
    | '/portal/tip403-factory'
    | '/portal/tip20-studio/$address/overview'
    | '/portal/tip20-studio/$address/rewards'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/portal/contacts'
    | '/portal/dashboard'
    | '/portal/liquidity'
    | '/portal/receive'
    | '/portal/scheduled'
    | '/portal/send'
    | '/portal/swap'
    | '/portal/tip20-studio'
    | '/portal/tip403-factory'
    | '/portal/tip20-studio/$address'
    | '/portal/tip403-factory/$policyId'
    | '/portal/tip20-studio/'
    | '/portal/tip403-factory/'
    | '/portal/tip20-studio/$address/overview'
    | '/portal/tip20-studio/$address/rewards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/tip403-factory': {
      id: '/portal/tip403-factory'
      path: '/tip403-factory'
      fullPath: '/portal/tip403-factory'
      preLoaderRoute: typeof PortalTip403FactoryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tip20-studio': {
      id: '/portal/tip20-studio'
      path: '/tip20-studio'
      fullPath: '/portal/tip20-studio'
      preLoaderRoute: typeof PortalTip20StudioRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/swap': {
      id: '/portal/swap'
      path: '/swap'
      fullPath: '/portal/swap'
      preLoaderRoute: typeof PortalSwapRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/send': {
      id: '/portal/send'
      path: '/send'
      fullPath: '/portal/send'
      preLoaderRoute: typeof PortalSendRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/scheduled': {
      id: '/portal/scheduled'
      path: '/scheduled'
      fullPath: '/portal/scheduled'
      preLoaderRoute: typeof PortalScheduledRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/receive': {
      id: '/portal/receive'
      path: '/receive'
      fullPath: '/portal/receive'
      preLoaderRoute: typeof PortalReceiveRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/liquidity': {
      id: '/portal/liquidity'
      path: '/liquidity'
      fullPath: '/portal/liquidity'
      preLoaderRoute: typeof PortalLiquidityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contacts': {
      id: '/portal/contacts'
      path: '/contacts'
      fullPath: '/portal/contacts'
      preLoaderRoute: typeof PortalContactsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tip403-factory/': {
      id: '/portal/tip403-factory/'
      path: '/'
      fullPath: '/portal/tip403-factory/'
      preLoaderRoute: typeof PortalTip403FactoryIndexRouteImport
      parentRoute: typeof PortalTip403FactoryRoute
    }
    '/portal/tip20-studio/': {
      id: '/portal/tip20-studio/'
      path: '/'
      fullPath: '/portal/tip20-studio/'
      preLoaderRoute: typeof PortalTip20StudioIndexRouteImport
      parentRoute: typeof PortalTip20StudioRoute
    }
    '/portal/tip403-factory/$policyId': {
      id: '/portal/tip403-factory/$policyId'
      path: '/$policyId'
      fullPath: '/portal/tip403-factory/$policyId'
      preLoaderRoute: typeof PortalTip403FactoryPolicyIdRouteImport
      parentRoute: typeof PortalTip403FactoryRoute
    }
    '/portal/tip20-studio/$address': {
      id: '/portal/tip20-studio/$address'
      path: '/$address'
      fullPath: '/portal/tip20-studio/$address'
      preLoaderRoute: typeof PortalTip20StudioAddressRouteImport
      parentRoute: typeof PortalTip20StudioRoute
    }
    '/portal/tip20-studio/$address/rewards': {
      id: '/portal/tip20-studio/$address/rewards'
      path: '/rewards'
      fullPath: '/portal/tip20-studio/$address/rewards'
      preLoaderRoute: typeof PortalTip20StudioAddressRewardsRouteImport
      parentRoute: typeof PortalTip20StudioAddressRoute
    }
    '/portal/tip20-studio/$address/overview': {
      id: '/portal/tip20-studio/$address/overview'
      path: '/overview'
      fullPath: '/portal/tip20-studio/$address/overview'
      preLoaderRoute: typeof PortalTip20StudioAddressOverviewRouteImport
      parentRoute: typeof PortalTip20StudioAddressRoute
    }
  }
}

interface PortalTip20StudioAddressRouteChildren {
  PortalTip20StudioAddressOverviewRoute: typeof PortalTip20StudioAddressOverviewRoute
  PortalTip20StudioAddressRewardsRoute: typeof PortalTip20StudioAddressRewardsRoute
}

const PortalTip20StudioAddressRouteChildren: PortalTip20StudioAddressRouteChildren =
  {
    PortalTip20StudioAddressOverviewRoute:
      PortalTip20StudioAddressOverviewRoute,
    PortalTip20StudioAddressRewardsRoute: PortalTip20StudioAddressRewardsRoute,
  }

const PortalTip20StudioAddressRouteWithChildren =
  PortalTip20StudioAddressRoute._addFileChildren(
    PortalTip20StudioAddressRouteChildren,
  )

interface PortalTip20StudioRouteChildren {
  PortalTip20StudioAddressRoute: typeof PortalTip20StudioAddressRouteWithChildren
  PortalTip20StudioIndexRoute: typeof PortalTip20StudioIndexRoute
}

const PortalTip20StudioRouteChildren: PortalTip20StudioRouteChildren = {
  PortalTip20StudioAddressRoute: PortalTip20StudioAddressRouteWithChildren,
  PortalTip20StudioIndexRoute: PortalTip20StudioIndexRoute,
}

const PortalTip20StudioRouteWithChildren =
  PortalTip20StudioRoute._addFileChildren(PortalTip20StudioRouteChildren)

interface PortalTip403FactoryRouteChildren {
  PortalTip403FactoryPolicyIdRoute: typeof PortalTip403FactoryPolicyIdRoute
  PortalTip403FactoryIndexRoute: typeof PortalTip403FactoryIndexRoute
}

const PortalTip403FactoryRouteChildren: PortalTip403FactoryRouteChildren = {
  PortalTip403FactoryPolicyIdRoute: PortalTip403FactoryPolicyIdRoute,
  PortalTip403FactoryIndexRoute: PortalTip403FactoryIndexRoute,
}

const PortalTip403FactoryRouteWithChildren =
  PortalTip403FactoryRoute._addFileChildren(PortalTip403FactoryRouteChildren)

interface PortalRouteChildren {
  PortalContactsRoute: typeof PortalContactsRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLiquidityRoute: typeof PortalLiquidityRoute
  PortalReceiveRoute: typeof PortalReceiveRoute
  PortalScheduledRoute: typeof PortalScheduledRoute
  PortalSendRoute: typeof PortalSendRoute
  PortalSwapRoute: typeof PortalSwapRoute
  PortalTip20StudioRoute: typeof PortalTip20StudioRouteWithChildren
  PortalTip403FactoryRoute: typeof PortalTip403FactoryRouteWithChildren
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalContactsRoute: PortalContactsRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLiquidityRoute: PortalLiquidityRoute,
  PortalReceiveRoute: PortalReceiveRoute,
  PortalScheduledRoute: PortalScheduledRoute,
  PortalSendRoute: PortalSendRoute,
  PortalSwapRoute: PortalSwapRoute,
  PortalTip20StudioRoute: PortalTip20StudioRouteWithChildren,
  PortalTip403FactoryRoute: PortalTip403FactoryRouteWithChildren,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
