/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalSwapRouteImport } from './routes/portal/swap'
import { Route as PortalStablecoinsRouteImport } from './routes/portal/stablecoins'
import { Route as PortalSendRouteImport } from './routes/portal/send'
import { Route as PortalScheduledRouteImport } from './routes/portal/scheduled'
import { Route as PortalReceiveRouteImport } from './routes/portal/receive'
import { Route as PortalLiquidityRouteImport } from './routes/portal/liquidity'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as PortalContactsRouteImport } from './routes/portal/contacts'
import { Route as PortalStablecoinsIndexRouteImport } from './routes/portal/stablecoins.index'
import { Route as PortalStablecoinsAddressRouteImport } from './routes/portal/stablecoins.$address'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSwapRoute = PortalSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStablecoinsRoute = PortalStablecoinsRouteImport.update({
  id: '/stablecoins',
  path: '/stablecoins',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSendRoute = PortalSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => PortalRoute,
} as any)
const PortalScheduledRoute = PortalScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReceiveRoute = PortalReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLiquidityRoute = PortalLiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContactsRoute = PortalContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStablecoinsIndexRoute = PortalStablecoinsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalStablecoinsRoute,
} as any)
const PortalStablecoinsAddressRoute =
  PortalStablecoinsAddressRouteImport.update({
    id: '/$address',
    path: '/$address',
    getParentRoute: () => PortalStablecoinsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/liquidity': typeof PortalLiquidityRoute
  '/portal/receive': typeof PortalReceiveRoute
  '/portal/scheduled': typeof PortalScheduledRoute
  '/portal/send': typeof PortalSendRoute
  '/portal/stablecoins': typeof PortalStablecoinsRouteWithChildren
  '/portal/swap': typeof PortalSwapRoute
  '/portal/stablecoins/$address': typeof PortalStablecoinsAddressRoute
  '/portal/stablecoins/': typeof PortalStablecoinsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/liquidity': typeof PortalLiquidityRoute
  '/portal/receive': typeof PortalReceiveRoute
  '/portal/scheduled': typeof PortalScheduledRoute
  '/portal/send': typeof PortalSendRoute
  '/portal/swap': typeof PortalSwapRoute
  '/portal/stablecoins/$address': typeof PortalStablecoinsAddressRoute
  '/portal/stablecoins': typeof PortalStablecoinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/liquidity': typeof PortalLiquidityRoute
  '/portal/receive': typeof PortalReceiveRoute
  '/portal/scheduled': typeof PortalScheduledRoute
  '/portal/send': typeof PortalSendRoute
  '/portal/stablecoins': typeof PortalStablecoinsRouteWithChildren
  '/portal/swap': typeof PortalSwapRoute
  '/portal/stablecoins/$address': typeof PortalStablecoinsAddressRoute
  '/portal/stablecoins/': typeof PortalStablecoinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/portal/contacts'
    | '/portal/dashboard'
    | '/portal/liquidity'
    | '/portal/receive'
    | '/portal/scheduled'
    | '/portal/send'
    | '/portal/stablecoins'
    | '/portal/swap'
    | '/portal/stablecoins/$address'
    | '/portal/stablecoins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/portal/contacts'
    | '/portal/dashboard'
    | '/portal/liquidity'
    | '/portal/receive'
    | '/portal/scheduled'
    | '/portal/send'
    | '/portal/swap'
    | '/portal/stablecoins/$address'
    | '/portal/stablecoins'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/portal/contacts'
    | '/portal/dashboard'
    | '/portal/liquidity'
    | '/portal/receive'
    | '/portal/scheduled'
    | '/portal/send'
    | '/portal/stablecoins'
    | '/portal/swap'
    | '/portal/stablecoins/$address'
    | '/portal/stablecoins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/swap': {
      id: '/portal/swap'
      path: '/swap'
      fullPath: '/portal/swap'
      preLoaderRoute: typeof PortalSwapRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/stablecoins': {
      id: '/portal/stablecoins'
      path: '/stablecoins'
      fullPath: '/portal/stablecoins'
      preLoaderRoute: typeof PortalStablecoinsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/send': {
      id: '/portal/send'
      path: '/send'
      fullPath: '/portal/send'
      preLoaderRoute: typeof PortalSendRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/scheduled': {
      id: '/portal/scheduled'
      path: '/scheduled'
      fullPath: '/portal/scheduled'
      preLoaderRoute: typeof PortalScheduledRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/receive': {
      id: '/portal/receive'
      path: '/receive'
      fullPath: '/portal/receive'
      preLoaderRoute: typeof PortalReceiveRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/liquidity': {
      id: '/portal/liquidity'
      path: '/liquidity'
      fullPath: '/portal/liquidity'
      preLoaderRoute: typeof PortalLiquidityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contacts': {
      id: '/portal/contacts'
      path: '/contacts'
      fullPath: '/portal/contacts'
      preLoaderRoute: typeof PortalContactsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/stablecoins/': {
      id: '/portal/stablecoins/'
      path: '/'
      fullPath: '/portal/stablecoins/'
      preLoaderRoute: typeof PortalStablecoinsIndexRouteImport
      parentRoute: typeof PortalStablecoinsRoute
    }
    '/portal/stablecoins/$address': {
      id: '/portal/stablecoins/$address'
      path: '/$address'
      fullPath: '/portal/stablecoins/$address'
      preLoaderRoute: typeof PortalStablecoinsAddressRouteImport
      parentRoute: typeof PortalStablecoinsRoute
    }
  }
}

interface PortalStablecoinsRouteChildren {
  PortalStablecoinsAddressRoute: typeof PortalStablecoinsAddressRoute
  PortalStablecoinsIndexRoute: typeof PortalStablecoinsIndexRoute
}

const PortalStablecoinsRouteChildren: PortalStablecoinsRouteChildren = {
  PortalStablecoinsAddressRoute: PortalStablecoinsAddressRoute,
  PortalStablecoinsIndexRoute: PortalStablecoinsIndexRoute,
}

const PortalStablecoinsRouteWithChildren =
  PortalStablecoinsRoute._addFileChildren(PortalStablecoinsRouteChildren)

interface PortalRouteChildren {
  PortalContactsRoute: typeof PortalContactsRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLiquidityRoute: typeof PortalLiquidityRoute
  PortalReceiveRoute: typeof PortalReceiveRoute
  PortalScheduledRoute: typeof PortalScheduledRoute
  PortalSendRoute: typeof PortalSendRoute
  PortalStablecoinsRoute: typeof PortalStablecoinsRouteWithChildren
  PortalSwapRoute: typeof PortalSwapRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalContactsRoute: PortalContactsRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLiquidityRoute: PortalLiquidityRoute,
  PortalReceiveRoute: PortalReceiveRoute,
  PortalScheduledRoute: PortalScheduledRoute,
  PortalSendRoute: PortalSendRoute,
  PortalStablecoinsRoute: PortalStablecoinsRouteWithChildren,
  PortalSwapRoute: PortalSwapRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
